# Here we RBAC the various networks
- name: decrypt clouds.yaml
  ansible.builtin.copy:
    decrypt: yes
    src: "{{playbook_dir}}/files/clouds-{{gc_tenancy | default(gc_cloud)}}.yaml"
    dest: "/tmp/{{ gc_cloud }}.yaml"
    mode: 0666
  when: admin_clouds_yaml is not defined

- name: Set clouds.yaml location if missing
  ansible.builtin.set_fact:
    admin_clouds_yaml: "/tmp/{{ gc_cloud }}.yaml"
  when: admin_clouds_yaml is not defined

- name: Get ID of common_ctrl network
  openstack.cloud.networks_info:
    cloud: openstack
    name: "{{control_network_name}}"
  register: ctrl_result
  environment:
    OS_CLIENT_CONFIG_FILE: "{{ admin_clouds_yaml }}"

- name: Debug ctrl_network result
  ansible.builtin.debug:
    msg: "Ctrl network output {{ ctrl_result }}"
# Ensure azimuth-vpod-common-ctrl RBAC policy exists

- name: Create common-ctrl network RBAC policy
  openstack.cloud.neutron_rbac_policy:
    object_id: "{{ ctrl_result.openstack_networks[0].id}}"
    object_type: "network"
    target_project_id: "{{appliance_project}}"
    project_id: "{{ctrl_result.openstack_networks[0].project_id}}"
    cloud: openstack
    action: "access_as_shared"
    state: present
  environment:
    OS_CLIENT_CONFIG_FILE: "{{ admin_clouds_yaml }}"

- name: Get ID of common_storage network
  openstack.cloud.networks_info:
    cloud: openstack
    name: "{{storage_network_name}}"
  register: storage_result
  environment:
    OS_CLIENT_CONFIG_FILE: "{{ admin_clouds_yaml }}"

# Ensure azimuth-vpod-common-storage RBAC policy exists
- name: Create common-storage network RBAC policy
  openstack.cloud.neutron_rbac_policy:
    object_id: "{{ storage_result.openstack_networks[0].id}}"
    object_type: "network"
    target_project_id: "{{appliance_project}}"
    project_id: "{{storage_result.openstack_networks[0].project_id}}"
    cloud: openstack
    action: "access_as_shared"
    state: present
  environment:
    OS_CLIENT_CONFIG_FILE: "{{ admin_clouds_yaml }}"

- name: Get ID of svc-storage network
  openstack.cloud.networks_info:
    cloud: openstack
    name: "{{svc_storage_network_name}}"
  register: svc_storage_result
  environment:
    OS_CLIENT_CONFIG_FILE: "{{ admin_clouds_yaml }}"

- name: Create svc-storage new network RBAC policy
  openstack.cloud.neutron_rbac_policy:
    object_id: "{{ svc_storage_result.openstack_networks[0].id}}"
    object_type: "network"
    target_project_id: "{{appliance_project}}"
    project_id: "{{svc_storage_result.openstack_networks[0].project_id}}"
    cloud: openstack
    action: "access_as_shared"
    state: present
  environment:
    OS_CLIENT_CONFIG_FILE: "{{ admin_clouds_yaml }}"
